backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/images/article-images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post"
    label: "post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta", name: "meta", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ['programming', 'hacking', 'security', 'news', 'tools', 'vulnhub', 'hackthebox'], multiple: true}
      - {label: "Image", name: "image", widget: "image", default: "card1-img.png"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "select", options: ['programming', 'security', 'white-hat', 'hex', 'hacking', 'ethical-hacking', 'code', 'security', courses, windows, cqure, advanced, elearnsecurity, ine.com], multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}
    
